#pragma once

UENUM(BlueprintType, Category = "Card Type")
namespace ECardTypePlaneswalker
{
	enum Type
	{
		None UMETA(DisplayName = "None"),
		Abian UMETA(DisplayName = "Abian"),
		Ajani UMETA(DisplayName = "Ajani"),
		Aminatou UMETA(DisplayName = "Aminatou"),
		Angrath UMETA(DisplayName = "Angrath"),
		Arlinn UMETA(DisplayName = "Arlinn"),
		Ashiok UMETA(DisplayName = "Ashiok"),
		BOB UMETA(DisplayName = "B.O.B."),
		Basri UMETA(DisplayName = "Basri"),
		Bolas UMETA(DisplayName = "Bolas"),
		Calix UMETA(DisplayName = "Calix"),
		Chandra UMETA(DisplayName = "Chandra"),
		Dack UMETA(DisplayName = "Dack"),
		Daretti UMETA(DisplayName = "Daretti"),
		Davriel UMETA(DisplayName = "Davriel"),
		Domri UMETA(DisplayName = "Domri"),
		Dovin UMETA(DisplayName = "Dovin"),
		Duck UMETA(DisplayName = "Duck"),
		Dungeon UMETA(DisplayName = "Dungeon"),
		Elspeth UMETA(DisplayName = "Elspeth"),
		Estrid UMETA(DisplayName = "Estrid"),
		Freyalise UMETA(DisplayName = "Freyalise"),
		Garruk UMETA(DisplayName = "Garruk"),
		Gideon UMETA(DisplayName = "Gideon"),
		Huatli UMETA(DisplayName = "Huatli"),
		Inzerva UMETA(DisplayName = "Inzerva"),
		Jace UMETA(DisplayName = "Jace"),
		Jaya UMETA(DisplayName = "Jaya"),
		Karn UMETA(DisplayName = "Karn"),
		Kasmina UMETA(DisplayName = "Kasmina"),
		Kaya UMETA(DisplayName = "Kaya"),
		Kiora UMETA(DisplayName = "Kiora"),
		Koth UMETA(DisplayName = "Koth"),
		Liliana UMETA(DisplayName = "Liliana"),
		Lukka UMETA(DisplayName = "Lukka"),
		Master UMETA(DisplayName = "Master"),
		Nahiri UMETA(DisplayName = "Nahiri"),
		Narset UMETA(DisplayName = "Narset"),
		Nissa UMETA(DisplayName = "Nissa"),
		Nixilis UMETA(DisplayName = "Nixilis"),
		Oko UMETA(DisplayName = "Oko"),
		Ral UMETA(DisplayName = "Ral"),
		Rowan UMETA(DisplayName = "Rowan"),
		Saheeli UMETA(DisplayName = "Saheeli"),
		Samut UMETA(DisplayName = "Samut"),
		Sarkhan UMETA(DisplayName = "Sarkhan"),
		Serra UMETA(DisplayName = "Serra"),
		Sorin UMETA(DisplayName = "Sorin"),
		Tamiyo UMETA(DisplayName = "Tamiyo"),
		Teferi UMETA(DisplayName = "Teferi"),
		Teyo UMETA(DisplayName = "Teyo"),
		Tezzeret UMETA(DisplayName = "Tezzeret"),
		Tibalt UMETA(DisplayName = "Tibalt"),
		Ugin UMETA(DisplayName = "Ugin"),
		Urza UMETA(DisplayName = "Urza"),
		Venser UMETA(DisplayName = "Venser"),
		Vivien UMETA(DisplayName = "Vivien"),
		Vraska UMETA(DisplayName = "Vraska"),
		Will UMETA(DisplayName = "Will"),
		Windgrace UMETA(DisplayName = "Windgrace"),
		Wrenn UMETA(DisplayName = "Wrenn"),
		Xenagos UMETA(DisplayName = "Xenagos"),
		Yanggu UMETA(DisplayName = "Yanggu"),
		Yanling UMETA(DisplayName = "Yanling")
	};
}
